name: Create repository
on:
  issues:
    types: [opened]

permissions:
  actions: write
  checks: write
  contents: write
  deployments: read
  issues: write
  packages: none
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  Create-Repo:
    runs-on: ubuntu-latest
    #if: contains(github.event.issues.labels.*.name, 'issueops')
    steps:
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Print Context
        uses: actions/github-script@v4
        with:
          script: |
            console.log(context)
            
      - name: Create GitHub repo
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.CUSTOM_TOKEN }}
          script: |
            console.log(context.payload.issue.body)
            
            bodySplit = context.payload.issue.body.split("\n")
            console.log("New repository name: " + bodySplit[2])
            console.log("Template Repository: " + bodySplit[6])
            console.log("Team: " + bodySplit[10])
            console.log("Enable Issue: " +  bodySplit[14].includes("X"))
            console.log("Enable Project: " +  bodySplit[18].includes("X"))
            console.log("Allow Squash Merge: " +  bodySplit[22].includes("X"))
            console.log("Allow Forking: " +  bodySplit[26].includes("X"))

            let newRepo = bodySplit[2]
            let templateRepo = bodySplit[6]
            let teams = bodySplit[10].split(",")
            let enableIssue = bodySplit[14].includes("X")
            let enableProject = bodySplit[18].includes("X")
            let enableSquashMerge = bodySplit[22].includes("X")
            let enableForking = bodySplit[26].includes("X")
            
            console.log("New repo: " + newRepo + " Template Repo: " + templateRepo + " Teams: " + teams)
            
            try {
              await github.rest.repos.createUsingTemplate({
                template_owner: context.payload.organization.login,
                template_repo: templateRepo,
                name: newRepo,
                owner: context.payload.organization.login,
                description: "Test",
                include_all_branches: true,
                private: false
              })
            } catch(err) {
                throw err 
            }
            
            try {
              await github.rest.repos.update({
                owner: context.payload.organization.login,
                private: true,
                repo: newRepo,
                has_issues: enableIssue,
                has_projects: enableProject,
                allow_squash_merge: enableSquashMerge
              })
            } catch(err) {
                throw err 
            }
            
            try {
              await github.rest.repos.updateBranchProtection({
                "owner": context.payload.organization.login,
                "repo": newRepo,
                "branch": 'main',
                "required_status_checks": { "strict": true, "contexts": [] },
                "enforce_admins": true,
                "required_pull_request_reviews": {"dismissal_restrictions": {"users":[], "teams":[]}, "dismiss_stale_reviews": false, "require_code_owner_reviews": true, "required_approving_review_count": 1},
                "restrictions" : { "users": [], "teams": [], "apps": [] }
              })
            } catch(err) {
                throw err 
            }
            
            try {
              await github.rest.teams.addOrUpdateRepoPermissionsInOrg({
                org: context.payload.organization.login,
                owner: context.payload.organization.login,
                repo: newRepo,
                team_slug: teams,
                permission: 'admin'
              })
            } catch(err) {
                throw err 
            }
            
            
      - name: Add comment
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thanks for creating a repo'
            })
            
            
            

          
      
         





